run:
  issues-exit-code: 1
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  gocyclo:
    # minimal code complexity to report
    min-complexity: 20
  maligned:
    suggest-new: false
  unused:
    check-exported: false
linters:
  enable:
    - errcheck
    - govet
    - golint
    - gofmt
    - gocyclo
  enable-all: false
  disable:
    - unused
    - structcheck
  disable-all: false