// Code generated by MockGen. DO NOT EDIT.
// Source: team-project/database (interfaces: TrainCrud)

// Package database is a generated GoMock package.
package database

import (
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	reflect "reflect"
	data "team-project/services/data"
)

// MockTrainCrud is a mock of TrainCrud interface
type MockTrainCrud struct {
	ctrl     *gomock.Controller
	recorder *MockTrainCrudMockRecorder
}

// MockTrainCrudMockRecorder is the mock recorder for MockTrainCrud
type MockTrainCrudMockRecorder struct {
	mock *MockTrainCrud
}

// NewMockTrainCrud creates a new mock instance
func NewMockTrainCrud(ctrl *gomock.Controller) *MockTrainCrud {
	mock := &MockTrainCrud{ctrl: ctrl}
	mock.recorder = &MockTrainCrudMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTrainCrud) EXPECT() *MockTrainCrudMockRecorder {
	return m.recorder
}

// AddTrain mocks base method
func (m *MockTrainCrud) AddTrain(arg0 data.Train) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTrain", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTrain indicates an expected call of AddTrain
func (mr *MockTrainCrudMockRecorder) AddTrain(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTrain", reflect.TypeOf((*MockTrainCrud)(nil).AddTrain), arg0)
}

// DeleteTrain mocks base method
func (m *MockTrainCrud) DeleteTrain(arg0 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrain", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTrain indicates an expected call of DeleteTrain
func (mr *MockTrainCrudMockRecorder) DeleteTrain(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrain", reflect.TypeOf((*MockTrainCrud)(nil).DeleteTrain), arg0)
}

// GetAllTrains mocks base method
func (m *MockTrainCrud) GetAllTrains() ([]data.Train, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTrains")
	ret0, _ := ret[0].([]data.Train)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTrains indicates an expected call of GetAllTrains
func (mr *MockTrainCrudMockRecorder) GetAllTrains() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTrains", reflect.TypeOf((*MockTrainCrud)(nil).GetAllTrains))
}

// GetTrain mocks base method
func (m *MockTrainCrud) GetTrain(arg0 string) (data.Train, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrain", arg0)
	ret0, _ := ret[0].(data.Train)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrain indicates an expected call of GetTrain
func (mr *MockTrainCrudMockRecorder) GetTrain(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrain", reflect.TypeOf((*MockTrainCrud)(nil).GetTrain), arg0)
}

// UpdateTrain mocks base method
func (m *MockTrainCrud) UpdateTrain(arg0 data.Train) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrain", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrain indicates an expected call of UpdateTrain
func (mr *MockTrainCrudMockRecorder) UpdateTrain(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrain", reflect.TypeOf((*MockTrainCrud)(nil).UpdateTrain), arg0)
}
